"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
<<<<<<< HEAD
=======
load_dotenv(dotenv_path=BASE_DIR / ".env")
print("Loaded DB host:", os.getenv("DB_HOST"))

>>>>>>> main


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mf2xmfe)x@+!9&e6&*$z6-k%@^z5p^!ra^8c(hax-qxef8fuom'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
"default": dj_database_url.config(
default="sqlite:///db.sqlite3",
conn_max_age=600, # persistent connections
ssl_require=True # enforce SSL
)
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

import os

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================================================================
# AUTHENTICATION & SESSION FIXES
# =========================================================================

# 1. Cookie Fix: REQUIRED for local development (http://localhost)
# If DEBUG is True and you are not using HTTPS, set these to False.
# If these are True, the browser will ignore the cookies on HTTP, causing the login loop.
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# 2. Redirect Definitions: Align views and settings
# Tells Django where to send users after a successful login
# Since your view redirects to 'browse', we use its path or name.
# Assuming 'browse' is mapped to path('/browse/', ...) in your urls.py
LOGIN_REDIRECT_URL = '/browse/'

# Tells Django where the login page is located (for @login_required decorator)
# If your view is mapped to path('login/', ..., name='login')
LOGIN_URL = '/login/' 

# 3. User Model (Best Practice - only necessary if 'accounts' is the app name)
# If you are using your own custom user model, this is critical. 
# Since you're using the default User model, it's safer to ensure this is set if 
# you plan to customize it later.
# If you have a custom user model in the 'accounts' app called 'CustomUser':
# AUTH_USER_MODEL = 'accounts.CustomUser' 
# Since you use the default, setting it may not be necessary, but defining it 
# makes your intentions clear.