# Generated by Django 5.2.6 on 2025-11-26 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_1', models.CharField(default='What is the name of your childhood best friend?', max_length=255)),
                ('answer_1_hash', models.CharField(max_length=255)),
                ('question_2', models.CharField(default='What city were you born in?', max_length=255)),
                ('answer_2_hash', models.CharField(max_length=255)),
                ('question_3', models.CharField(default='What was the name of your first pet?', max_length=255)),
                ('answer_3_hash', models.CharField(max_length=255)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_questions',
                'managed': True,
            },
        ),
    ]
