# Generated by Django 5.2.6 on 2025-11-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userfavorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorites',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='franchisor',
            name='location',
            field=models.CharField(blank=True, help_text='City, State/Province, Country (e.g., Manila, Philippines)', max_length=255, null=True),
        ),
    ]
