# Generated by Django 5.2.6 on 2025-11-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_franchise_franchiseapplication_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='franchisee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='franchisor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
