# Generated by Django 5.2.6 on 2025-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userfavorites_options_franchisor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload franchise brochure (PDF, DOC, DOCX, etc.)', null=True, upload_to='franchise_documents/'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='business_plan',
            field=models.FileField(blank=True, help_text='Upload business plan document (PDF, DOC, DOCX, etc.)', null=True, upload_to='franchise_documents/'),
        ),
    ]
