# Generated by Django 5.2.7 on 2025-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_franchiseapplication_options_adminprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseapplication',
            name='approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchiseapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Accepted', 'Accepted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
