# Generated by Django 5.2.6 on 2025-12-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_franchise_brochure_franchise_business_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseapplication',
            name='business_proposal',
            field=models.FileField(blank=True, help_text='Upload your business proposal (PDF, DOC, DOCX)', null=True, upload_to='application_documents/'),
        ),
        migrations.AddField(
            model_name='franchiseapplication',
            name='financial_statement',
            field=models.FileField(blank=True, help_text='Upload financial statement or proof of funds (PDF)', null=True, upload_to='application_documents/'),
        ),
        migrations.AddField(
            model_name='franchiseapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume/CV (PDF, DOC, DOCX)', null=True, upload_to='application_documents/'),
        ),
    ]
