# Generated by Django 5.2.7 on 2025-12-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_franchiseapplication_business_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchiseapplication',
            name='business_proposal',
            field=models.FileField(blank=True, help_text='Upload your business proposal (PDF, DOC, DOCX)', max_length=500, null=True, upload_to='application_documents/'),
        ),
        migrations.AlterField(
            model_name='franchiseapplication',
            name='financial_statement',
            field=models.FileField(blank=True, help_text='Upload financial statement or proof of funds (PDF)', max_length=500, null=True, upload_to='application_documents/'),
        ),
        migrations.AlterField(
            model_name='franchiseapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume/CV (PDF, DOC, DOCX)', max_length=500, null=True, upload_to='application_documents/'),
        ),
    ]
