# Generated by Django 5.2.6 on 2025-11-25 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_franchiseapplication_approval_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, choices=[('first_time', 'First-time franchisee'), ('experienced_owner', 'Experienced business owner'), ('corporate_executive', 'Corporate executive'), ('others', 'Others')], max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('agree_terms', models.BooleanField(default=False)),
                ('subscribe', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='accounts.franchise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'franchise_inquiry',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
